[project]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
description = "Add a short description here"
name = "mochess"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "*"
